name: Compress images
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@develop
      - name: Compress Images
        uses: calibreapp/image-actions@develop
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
